spring:
  profiles:
    active:
    - development

camel:
  springboot:
    name: estafet-microservices-scrum-gateway
  component:
    servlet:
      mapping:
        enabled: true
  hystrix:
    group-key: CamelHystrix
    circuit-breaker-enabled: true
    execution-timeout-enabled: true
    execution-timeout-in-milliseconds: 100000
    execution-isolation-strategy: THREAD
    circuit-breaker-error-threshold-percentage: 10
    circuit-breaker-request-volume-threshold: 40
    circuit-breaker-sleep-window-in-milliseconds: 5000

        
security:
  basic:
    enabled: false

management:
  security:
    enabled: false

#endpoints:
#  enabled: false
#  health:
#    enabled: true
  
application:
  estafet:
    projectUrl: http://project-api.microservices-scrum.svc:8080
    sprintUrl: http://sprint-api.microservices-scrum.svc:8080
    storyUrl: http://story-api.microservices-scrum.svc:8080
    taskUrl: http://task-api.microservices-scrum.svc:8080
---

spring:
  profiles: development
  
server:
  port: 8085 
 
application:
  estafet:
    projectUrl: http://localhost:8086
    sprintUrl:  http://localhost:8088
    storyUrl: http://localhost:8089
    taskUrl: http://localhost:8090