spring:
  profiles:
      active:
#      - development
#      - openshift-dev
       
camel:
  springboot:
    name: estafet-microservices-scrum-gateway
  component:
    servlet:
      mapping:
        enabled: true 
  hystrix:
    group-key: CamelHystrix
    circuit-breaker-enabled: true
    execution-timeout-enabled: true
    execution-timeout-in-milliseconds: 500
    execution-isolation-strategy: THREAD
    circuit-breaker-error-threshold-percentage: 10
    circuit-breaker-request-volume-threshold: 40
    circuit-breaker-sleep-window-in-milliseconds: 5000

eureka:
  client:
    healthCheck:
      enabled: true
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://discovery.microservices-scrum.svc:8080/eureka}
  instance:
    preferIpAddress: true
      
security:
  basic:
    enabled: false

management:
  security:
    enabled: false

#endpoints:
#  enabled: false
#  health:
#    enabled: true
  
application:
  services:
    project-api: http://project-api.microservices-scrum.svc:8080
    sprint-api: http://sprint-api.microservices-scrum.svc:8080
    story-api: http://story-api.microservices-scrum.svc:8080
    task-api: http://task-api.microservices-scrum.svc:8080
---

spring:
  profiles: development


eureka:
  client:
    healthCheck: 
      enabled: true
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://localhost:8090/eureka}
  instance:
    preferIpAddress: true
     
server:
  port: 8085 
 
application:
  services:
    project-api: http://localhost:8086
    sprint-api:  http://localhost:8088
    story-api: http://localhost:8089
    task-api: http://localhost:8090
    
---

spring:
  profiles: openshift-dev
  
camel:
  springboot:
    jmx-enabled: false
     
eureka:
  client:
    healthCheck: 
      enabled: true
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://discovery-microservices-scrum.192.168.99.100.nip.io/eureka}
  instance:
    preferIpAddress: true
     
server:
  port: 8085
 
application:
  services:
    project-api: http://project-api-microservices-scrum.192.168.99.100.nip.io
    sprint-api:  http://estafet-microservices-scrum-sprint.192.168.99.100.nip.io
    story-api: http://estafet-microservices-scrum-story.192.168.99.100.nip.io
    task-api: http://estafet-microservices-scrum-task.192.168.99.100.nip.io
  